### ISSUE TITLE
紧急求助：哪个方法可以实现AVRootView大小变化的时候，播放画面也随AVRootView变化？

### ISSUE THREAD

**Issue by justziyang** [zhaoyang21cn/iLiveSDK_Android_LiveDemo#4]
android在观众端，手机竖直的时候AVRootView为半屏播放，点击全屏按钮后隐藏其他布局，此时AVRootView变为全屏大小，但是AVVideoView画面还是半屏大小的画面。求指导调用哪个方法可以实现AVRootView大小变化的时候，播放画面也随AVRootView变化？
图片请参考论坛链接。
http://bbs.qcloud.com/thread-42222-1-1.html

**Comment by xkazer** [comment]
sdk目前不会自动根据AVRootView调整视频画面AVVideoView的尺寸，需要业务层在变更时自己修改AVVideoView的尺寸，方法如下:
setPosTop、setPosLeft、setPosWidth、setPosHeight

**Comment by xkazer** [comment]
新版本中添监听AVRootView的尺寸变更事件，同步调整AVVideoView，并上抛onSubCreated事件
