### ISSUE TITLE
我用demo运行，换成自己的appid,加入房间的时候会报10015 invalid group id 

### ISSUE THREAD

**Issue by lvdong** [zhaoyang21cn/iLiveSDK_Android_LiveDemo#6]
像这种是哪里配置的原因吗？用demo的就没问题。是哪里要配置权限么

**Comment by dengqicheng** [comment]
ERR_UGC_FILE_NAME     视频上传文件名太长（超过 40）或含有特殊字符   这都半年前了

**Comment by xkazer** [comment]
加入房间时若imsupport为true，则会加入IM群组，"10015 invalid group id"表示option中配置的群组id无效
